# Schema for the configuration file of the VWO module.
vwo.settings:
  type: config_object
  label: VWO module settings
  mapping:
    id:
      type: integer
      label: 'VWO Account ID'
      nullable: true
    filter:
      type: mapping
      label: 'Visibility settings'
      mapping:
        enabled:
          type: string
          label: 'Visibility filter enabled'
        userconfig:
          type: string
          label: 'User choice visibility'
        nodetypes:
          type: sequence
          label: 'Content type visibility selections'
          sequence:
            type: string
            label: 'Content type machine names'
        page:
          type: mapping
          label: 'Page path visibility'
          mapping:
            type:
              type: string
              label: 'In/Exclude pages'
            list:
              type: string
              label: 'List of paths to compare'
              nullable: true
        roles:
          type: sequence
          label: 'User role visibility selections'
          sequence:
            type: string
            label: 'Role machine names'
    loading:
      type: mapping
      label: 'JS loading method settings'
      mapping:
        type:
          type: string
          label: '(A)synchronosity setting'
        timeout:
          type: mapping
          label: 'JS timeout settings'
          mapping:
            settings:
              type: integer
              label: 'Settings load timeout'
            library:
              type: integer
              label: 'Library load timeout'
        usejquery:
          type: string
          label: 'Use system jQuery'
